using System.Text;
using DOTL.Core.Elements;
using DOTL.Core.Parser.AST;
using DOTL.Core.Runtime;

namespace DOTL.Core.Generator
{
    public class HtmlGenerator
    {
        private readonly ElementRegistry _registry;

        public HtmlGenerator()
        {
            _registry = new ElementRegistry();
        }

        public string Generate(List<ASTNode> astNodes)
        {
            // Clear any previous state
            _registry.Clear();

            // Process all AST nodes
            foreach (var node in astNodes)
            {
                ProcessNode(node);
            }

            // Generate HTML from root elements
            return GenerateHtml();
        }

        private void ProcessNode(ASTNode node)
        {
            switch (node)
            {
                case ElementCreationNode creationNode:
                    ProcessElementCreation(creationNode);
                    break;

                case PropertyAssignmentNode propertyNode:
                    ProcessPropertyAssignment(propertyNode);
                    break;

                case ContainerAddNode addNode:
                    ProcessContainerAdd(addNode);
                    break;

                default:
                    throw new InvalidOperationException($"Unknown AST node type: {node.GetType().Name}");
            }
        }

        private void ProcessElementCreation(ElementCreationNode node)
        {
            var element = ElementFactory.CreateElement(node.ElementType, node.VariableName);
            _registry.RegisterElement(node.VariableName, element);
        }

        private void ProcessPropertyAssignment(PropertyAssignmentNode node)
        {
            _registry.SetProperty(node.VariableName, node.PropertyName, node.Value);
        }

        private void ProcessContainerAdd(ContainerAddNode node)
        {
            _registry.AddChild(node.ContainerVariableName, node.ChildVariableName);
        }

        private string GenerateHtml()
        {
            var builder = new StringBuilder();

            builder.AppendLine("<!DOCTYPE html>");
            builder.AppendLine("<html>");
            builder.AppendLine("  <head>");
            builder.AppendLine("    <meta charset=\"UTF-8\">");
            builder.AppendLine("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
            builder.AppendLine("    <title>Generated by DOTL</title>");
            builder.AppendLine("  </head>");
            builder.AppendLine("  <body>");

            var rootElements = _registry.GetRootElements();

            if (!rootElements.Any())
            {
                builder.AppendLine("    <!-- No elements defined -->");
            }
            else
            {
                foreach (var element in rootElements)
                {
                    var elementHtml = element.GenerateHtml(2); // Indent by 2 levels (4 spaces)
                    builder.Append(elementHtml);
                    builder.AppendLine();
                }
            }

            builder.AppendLine("  </body>");
            builder.AppendLine("</html>");

            return builder.ToString();
        }
    }
}